-- Using the code from the preceding three exercises, implement Graham’s scan algorithm for the convex hull of a set of 2D points. 
-- You can find good description of what a convex hull (http://en.wikipedia.org/wiki/Convex_hull) is, 
-- and how the Graham scan algorithm (http://en.wikipedia.org/wiki/Graham_scan) should work, on Wikipedia (http://en.wikipedia.org/).
