-- The * wild card matches names only within a single directory. 
-- Many shells have an extended wild card syntax, **, that matches names recursively in all directories. 
-- For example, **.c would mean “match a name ending in .c in this directory or any subdirectory at any depth”. 
-- Implement matching on ** wild cards.
