--  Write your own “safe” definitions of the standard partial list functions, but make sure they never fail. As a hint, you might want to consider using the following types:
-- file: ch04/ch04.exercises.hs
--   safeHead :: [a] -> Maybe a
--   safeTail :: [a] -> Maybe [a]
--   safeLast :: [a] -> Maybe a
--   safeInit :: [a] -> Maybe [a]
